#!/usr/bin/env python3
import os
import re

BASE_DIR = (
    "/Users/chulheewon/development/main_project/homepage_dream/multi_clone_hompage/home"
)

TRANSLATIONS = {
    "Project 상담": "Project Consultation",
    "Project 포트폴리오": "Project Portfolio",
    "Project 유형": "Project Type",
    "Project 규모": "Project Scale",
    "Project 내용": "Project Details",
    "조경 Design": "Landscape Design",
    "리노베이션": "Renovation",
    "Design 컨설팅": "Design Consulting",
    "3D 시각화": "3D Visualization",
    "Design 프로세스": "Design Process",
    "실시 Design": "Schematic Design",
    "상업": "Commercial",
    "주거": "Residential",
    "문화": "Cultural",
    "리조트": "Resort",
    "호텔": "Hotel",
    "오피스": "Office",
    "콘셉트 기획": "Concept Planning",
    "리서치": "Research",
    "Basic Design": "Basic Design",
    "스케치": "Sketch",
    "Construction 감리": "Construction Supervision",
    "품질 관리": "Quality Control",
    "수상": "Awards",
    "수상 & 인증": "Awards & Certifications",
    "한국건축문화대상": "Korea Architecture Culture Award",
    "대상": "Grand Prize",
    "김수근건축상": "Kim Su-geun Architecture Award",
    "본상": "Main Prize",
    "서울시건축상": "Seoul Architecture Award",
    "우수상": "Excellence Award",
    "평일": "Weekdays",
    "서울시": "Seoul",
    "서울시 강남구": "Gangnam-gu, Seoul",
    "이름": "Name",
    "홍길동": "John Doe",
    "이메일": "Email",
    "유형 Optional": "Type (Optional)",
    "Project에 대해 간략히 설명해 주세요.": "Please describe your project briefly.",
    "예: 200평, 3층 규모": "e.g., 200 pyeong, 3-story building",
    "상담 문의": "Contact Us",
    "이용약관": "Terms of Service",
    "개인정보처리방침": "Privacy Policy",
    "전송 Completed!": "Sent Completed!",
    "리노베이션": "Renovation",
    "Design": "Design",
    "Process": "Process",
    "2주": "2 weeks",
    "4주": "4 weeks",
    "6주": "6 weeks",
    "24주": "24 weeks",
    "Architect": "Architect",
    "Engineering": "Engineering",
    "Contact": "Contact",
    "Services": "Services",
    "Projects": "Projects",
    "About": "About",
    "Home": "Home",
    "Menu": "Menu",
    "제품": "Product",
    "서비스": "Service",
    "정보": "Information",
    "문의": "Inquiry",
    "클릭": "Click",
    "자세히": "More",
    "더보기": "Read More",
    "이전": "Previous",
    "다음": "Next",
    "검색": "Search",
    "메뉴": "Menu",
    "홈": "Home",
    "자동 차": "Auto Detail",
    "자동차": "Car",
    "베이커리": "Bakery",
    "빵": "Bread",
    "카페": "Cafe",
    "음식": "Food",
    "음료": "Drinks",
    "예약": "Reservation",
    "예약하기": "Book Now",
    "리뷰": "Review",
    "후기": "Reviews",
    "위치": "Location",
    "주소": "Address",
    "전화": "Phone",
    "연락처": "Contact",
    "영업시간": "Business Hours",
    "가격": "Price",
    "메뉴판": "Menu",
    "테마": "Theme",
    "인테리어": "Interior",
    "사진": "Photos",
    "갤러리": "Gallery",
    "이벤트": "Event",
    "할인": "Discount",
    "쿠폰": "Coupon",
    "신규": "New",
    "인기": "Popular",
    "추천": "Recommended",
    "특별": "Special",
    "한식": "Korean Food",
    "일식": "Japanese Food",
    "중식": "Chinese Food",
    "양식": "Western Food",
    "고기": "Meat",
    "해산물": "Seafood",
    "채소": "Vegetables",
    "밥": "Rice",
    "면": "Noodles",
    "국": "Soup",
    "디저트": "Dessert",
    "커피": "Coffee",
    "차": "Tea",
    "주스": "Juice",
    "맥주": "Beer",
    "와인": "Wine",
    "위스키": "Whiskey",
    "클럽": "Club",
    "바": "Bar",
    "펍": "Pub",
    "클래스": "Class",
    "강좌": "Course",
    "워크숍": "Workshop",
    "체험": "Experience",
    "투어": "Tour",
    "여행": "Travel",
    "호텔": "Hotel",
    "펜션": "Pension",
    "게스트하우스": "Guesthouse",
    "모텔": "Motel",
    "에어비앤비": "Airbnb",
    "예약": "Reservation",
    "체크인": "Check-in",
    "체크아웃": "Check-out",
    "게스트": "Guest",
    "침대": "Bed",
    "방": "Room",
    "스위트": "Suite",
    "더블": "Double",
    "트윈": "Twin",
    "트리플": "Triple",
    "싱글": "Single",
    "조식": "Breakfast",
    "중식": "Lunch",
    "석식": "Dinner",
    "뷔페": "Buffet",
    "룸서비스": "Room Service",
    "와이파이": "WiFi",
    "주차": "Parking",
    "수영장": "Pool",
    "헬스장": "Gym",
    "사우나": "Sauna",
    "스파": "Spa",
    "마사지": "Massage",
    "피트니스": "Fitness",
    "요가": "Yoga",
    "필라테스": "Pilates",
    "수영": "Swimming",
    "골프": "Golf",
    "테니스": "Tennis",
    "배드민턴": "Badminton",
    "농구": "Basketball",
    "축구": "Soccer",
    "야구": "Baseball",
    "레슬링": "Wrestling",
    "권투": "Boxing",
    "복싱": "Boxing",
    "킥복싱": "Kickboxing",
    "태권도": "Taekwondo",
    "유도": "Judo",
    "가라테": "Karate",
    "합기도": "Hapkido",
    "무술": "Martial Arts",
    "보건소": "Health Center",
    "병원": "Hospital",
    "클리닉": "Clinic",
    "의사": "Doctor",
    "간호사": "Nurse",
    "치과": "Dental",
    "치과병원": "Dental Clinic",
    "이비인후과": "ENT",
    "피부과": "Dermatology",
    "정형외과": "Orthopedics",
    "산부인과": "Obstetrics",
    "소아과": "Pediatrics",
    "내과": "Internal Medicine",
    "외과": "Surgery",
    "신경과": "Neurology",
    "정신과": "Psychiatry",
    "안과": "Ophthalmology",
    "비뇨기과": "Urology",
    "한의원": "Korean Medicine",
    "동물병원": "Veterinary",
    "반려동물": "Pet",
    "애완동물": "Pet",
    "고양이": "Cat",
    "개": "Dog",
    "새": "Bird",
    "물고기": "Fish",
    "햄스터": "Hamster",
    "토끼": "Rabbit",
    "미용": "Beauty",
    "헤어": "Hair",
    "피부": "Skin",
    "네일": "Nail",
    "왁싱": "Waxing",
    "메이크업": "Makeup",
    "스킨케어": "Skincare",
    "마사지": "Massage",
    "왁싱": "Waxing",
    "뷰티": "Beauty",
    "살롱": "Salon",
    "샵": "Shop",
    "스토어": "Store",
    "부티크": "Boutique",
    "아울렛": "Outlet",
    "백화점": "Department Store",
    "면세점": "Duty Free",
    "시장": "Market",
    "장터": "Flea Market",
    "공방": "Workshop",
    "학원": "Academy",
    "학교": "School",
    "대학교": "University",
    "대학원": "Graduate School",
    "도서관": "Library",
    "박물관": "Museum",
    "미술관": "Art Gallery",
    "전시관": "Exhibition Hall",
    "극장": "Theater",
    "영화관": "Cinema",
    "콘서트": "Concert",
    "페스티벌": "Festival",
    "파티": "Party",
    "이벤트": "Event",
    "세미나": "Seminar",
    "컨퍼런스": "Conference",
    "博览会": "Expo",
    "박람회": "Expo",
    "展示": "Exhibition",
    "취업": "Employment",
    "채용": "Recruitment",
    "지원": "Apply",
    "접수": "Reception",
    "마감": "Deadline",
    "결과": "Result",
    "합격": "Pass",
    "불합격": "Fail",
    "면접": "Interview",
    "서류": "Document",
    "경력": "Career",
    "경력사항": "Work Experience",
    "자격증": "License",
    "학력": "Education",
    "이력서": "Resume",
    "포트폴리오": "Portfolio",
    "简历": "Resume",
    "명함": "Business Card",
    "카드": "Card",
    "현금": "Cash",
    "카드": "Card",
    "계좌": "Account",
    "이체": "Transfer",
    " 송금": "Transfer",
    "결제": "Payment",
    "청구": "Invoice",
    "영수증": "Receipt",
    "가격표": "Price List",
    "메뉴": "Menu",
    "주문": "Order",
    "주문하기": "Order Now",
    "장바구니": "Cart",
    "결제하기": "Checkout",
    "배송": "Shipping",
    "배달": "Delivery",
    "도착": "Arrival",
    "발송": "Shipped",
    "취소": "Cancel",
    "환불": "Refund",
    "교환": "Exchange",
    "반품": "Return",
    "A/S": "After Service",
    "품질": "Quality",
    "보증": "Warranty",
    "gar": "Warranty",
    "AS": "After Service",
    "신속": "Fast",
    "정확": "Accurate",
    "친절": "Friendly",
    "편리": "Convenient",
    "舒适": "Comfortable",
    "편안": "Comfortable",
    "감사": "Thank You",
    "감사합니다": "Thank You",
    "안녕하세요": "Hello",
    "안녕": "Bye",
    "再见": "Goodbye",
    "다음에 봐요": "See You Next Time",
    "어서 오세요": "Welcome",
    "감사합니다": "Thank You",
    "죄송합니다": "Sorry",
    "실례합니다": "Excuse Me",
    "도와드릴까요": "Can I Help You",
    "필요한 건 없어요": "Is There Anything You Need",
    "천천히": "Take Your Time",
    "좋아요": "OK",
    "네": "Yes",
    "아니요": "No",
    "좋은": "Good",
    "빠른": "Fast",
    "느린": "Slow",
    "큰": "Big",
    "작은": "Small",
    "새로운": "New",
    "오래된": "Old",
    "좋은": "Good",
    "나쁜": "Bad",
    "예쁜": "Beautiful",
    "멋진": "Cool",
    "재미있는": "Fun",
    "无聊": "Boring",
    "재미없": "Boring",
    "어려운": "Difficult",
    "쉬운": "Easy",
    "비싼": "Expensive",
    "저렴한": "Cheap",
    "免费": "Free",
    "무료": "Free",
    "유료": "Paid",
    "할인": "Discount",
    "세일": "Sale",
    "추가": "Additional",
    "기본": "Basic",
    "고급": "Premium",
    "최상": "Top",
    "최하": "Bottom",
    "위": "Top",
    "아래": "Below",
    "옆": "Next",
    "뒤": "Back",
    "앞": "Front",
    "중앙": "Center",
    "왼쪽": "Left",
    "오른쪽": "Right",
    "동쪽": "East",
    "서쪽": "West",
    "남쪽": "South",
    "북쪽": "North",
    "년": "Year",
    "월": "Month",
    "일": "Day",
    "시": "Hour",
    "분": "Minute",
    "초": "Second",
    "오늘": "Today",
    "어제": "Yesterday",
    "내일": "Tomorrow",
    "다음 주": "Next Week",
    "지난 주": "Last Week",
    "이번 달": "This Month",
    "다음 달": "Next Month",
    "번": "Times",
    "회": "Times",
    "명": "People",
    "명": "Person",
    "개": "Items",
    "명": "People",
    "cm": "cm",
    "mm": "mm",
    "m": "m",
    "km": "km",
    "kg": "kg",
    "g": "g",
    "ml": "ml",
    "L": "L",
    "℃": "℃",
    "℉": "℉",
    "₩": "$",
    "원": "KRW",
    "亿": "Billion",
    "억": "Billion",
    "만": "10 Thousand",
    "천": "Thousand",
    "백": "Hundred",
    "십": "Ten",
    "一": "One",
    "이": "Two",
    "삼": "Three",
    "사": "Four",
    "오": "Five",
    "육": "Six",
    "칠": "Seven",
    "팔": "Eight",
    "구": "Nine",
    "십": "Ten",
}

KOREAN_FOLDERS = [
    "architecture",
    "auto-detail",
    "bookstore",
    "boutique-hotel",
    "cafe-lounge",
    "cooking-studio",
    "cowork-space",
    "craft-brewery",
    "dental-clinic",
    "ev-station",
    "fine-dining",
    "fitness-gym",
    "flower-boutique",
    "hair-salon",
    "jewelry-atelier",
    "law-firm",
    "music-studio",
    "organic-farm",
    "pet-clinic",
    "photo-studio",
    "pilates-studio",
    "real-estate",
    "spa-wellness",
    "surf-school",
    "tattoo-studio",
    "watch-atelier",
    "whiskey-lounge",
    "wine-bar",
    "yacht-club",
]


def translate_file(filepath):
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()

    original = content

    for korean, english in TRANSLATIONS.items():
        content = content.replace(korean, english)

    if content != original:
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)
        return True
    return False


total = 0
changed = 0

for folder in KOREAN_FOLDERS:
    folder_path = os.path.join(BASE_DIR, folder, "index.html")
    if os.path.exists(folder_path):
        total += 1
        if translate_file(folder_path):
            changed += 1
            print(f"✓ Translated: {folder}")
        else:
            print(f"- No changes: {folder}")

print(f"\nTotal: {total}, Changed: {changed}")
