import "dotenv/config";
import pg from "pg";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../src/generated/prisma/client";

const pool = new pg.Pool({ connectionString: process.env.DIRECT_URL });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter } as any);

const templates = [
  { slug: "cafe-lounge", title: "BREWED — Premium Cafe & Lounge", description: "한 잔의 커피로 시작되는 특별한 하루. 따뜻한 카페 & 라운지 랜딩 페이지", price: 15, category: "pages", tags: ["cafe", "lounge", "korean", "warm"], language: "한국어", style: ["dark-theme", "warm", "serif"], layout: "centered", sourceUrl: "https://brewed-cafe.kr", thumbnailUrl: "/templates/cafe-lounge/images/fullpage.png", htmlPath: "/templates/cafe-lounge/index.html", sections: ["header", "hero", "feature", "stats", "testimonial", "faq", "contact", "footer"] },
  { slug: "law-firm", title: "LEXUS & PARTNERS — Law Firm", description: "신뢰와 전문성의 법률 사무소 랜딩 페이지", price: 18, category: "pages", tags: ["law", "firm", "professional", "korean"], language: "한국어", style: ["dark-theme", "elegant", "serif"], layout: "centered", sourceUrl: "https://lexus-law.kr", thumbnailUrl: "/templates/law-firm/images/fullpage.png", htmlPath: "/templates/law-firm/index.html", sections: ["header", "hero", "stats", "feature", "testimonial", "faq", "contact", "footer"] },
  { slug: "fitness-gym", title: "FORGE FITNESS — Performance Center", description: "Bold and energetic fitness center landing page with diagonal layouts", price: 15, category: "pages", tags: ["fitness", "gym", "bold", "energy"], language: "English", style: ["dark-theme", "bold", "gradient"], layout: "centered", sourceUrl: "https://forge-fitness.com", thumbnailUrl: "/templates/fitness-gym/images/fullpage.png", htmlPath: "/templates/fitness-gym/index.html", sections: ["header", "hero", "feature", "stats", "pricing", "testimonial", "faq", "contact", "footer"] },
  { slug: "real-estate", title: "PRIME REALTY — Premium Properties", description: "Premium real estate landing with property showcase and trust signals", price: 20, category: "pages", tags: ["real-estate", "property", "premium", "modern"], language: "English", style: ["dark-theme", "modern", "minimal"], layout: "centered", sourceUrl: "https://prime-realty.com", thumbnailUrl: "/templates/real-estate/images/fullpage.png", htmlPath: "/templates/real-estate/index.html", sections: ["header", "hero", "feature", "stats", "contact", "footer"] },
  { slug: "fine-dining", title: "MAISON NOIR — Fine Dining", description: "고급 파인다이닝 레스토랑을 위한 시네마틱 랜딩 페이지", price: 22, category: "pages", tags: ["dining", "restaurant", "luxury", "korean"], language: "한국어", style: ["dark-theme", "elegant", "serif"], layout: "centered", sourceUrl: "https://maison-noir.kr", thumbnailUrl: "/templates/fine-dining/images/fullpage.png", htmlPath: "/templates/fine-dining/index.html", sections: ["header", "hero", "feature", "stats", "testimonial", "faq", "contact", "footer"] },
  { slug: "dental-clinic", title: "SMILE DENTAL — Modern Clinic", description: "모던한 치과 클리닉 랜딩 페이지", price: 16, category: "pages", tags: ["dental", "clinic", "medical", "korean"], language: "한국어", style: ["dark-theme", "modern", "minimal"], layout: "centered", sourceUrl: "https://smile-dental.kr", thumbnailUrl: "/templates/dental-clinic/images/fullpage.png", htmlPath: "/templates/dental-clinic/index.html", sections: ["header", "hero", "feature", "how-it-works", "stats", "testimonial", "faq", "contact", "footer"] },
  { slug: "photo-studio", title: "LUMIERE STUDIO — Photography", description: "Creative photography studio with masonry gallery and lightbox", price: 18, category: "pages", tags: ["photography", "studio", "creative", "gallery"], language: "English", style: ["dark-theme", "modern", "bold"], layout: "centered", sourceUrl: "https://lumiere-photo.com", thumbnailUrl: "/templates/photo-studio/images/fullpage.png", htmlPath: "/templates/photo-studio/index.html", sections: ["header", "hero", "feature", "stats", "testimonial", "faq", "contact", "footer"] },
  { slug: "flower-boutique", title: "PETALE — Flower Boutique", description: "로맨틱한 꽃가게 부티크 랜딩 페이지", price: 15, category: "pages", tags: ["flower", "boutique", "romantic", "korean"], language: "한국어", style: ["dark-theme", "elegant", "warm"], layout: "centered", sourceUrl: "https://petale-flower.kr", thumbnailUrl: "/templates/flower-boutique/images/fullpage.png", htmlPath: "/templates/flower-boutique/index.html", sections: ["header", "hero", "feature", "stats", "testimonial", "faq", "contact", "footer"] },
  { slug: "hair-salon", title: "ATELIER HAIR — Premium Salon", description: "프리미엄 헤어 살롱 랜딩 페이지", price: 16, category: "pages", tags: ["hair", "salon", "beauty", "korean"], language: "한국어", style: ["dark-theme", "elegant", "gradient"], layout: "centered", sourceUrl: "https://atelier-hair.kr", thumbnailUrl: "/templates/hair-salon/images/fullpage.png", htmlPath: "/templates/hair-salon/index.html", sections: ["header", "hero", "feature", "pricing", "testimonial", "faq", "contact", "footer"] },
  { slug: "architecture", title: "FORMA ARCHITECTS — Design Studio", description: "Architecture studio with blueprint animations and project timeline", price: 20, category: "pages", tags: ["architecture", "studio", "design", "blueprint"], language: "English", style: ["dark-theme", "modern", "bold"], layout: "centered", sourceUrl: "https://forma-arch.com", thumbnailUrl: "/templates/architecture/images/fullpage.png", htmlPath: "/templates/architecture/index.html", sections: ["header", "hero", "stats", "feature", "how-it-works", "testimonial", "faq", "contact", "footer"] },
  { slug: "pet-clinic", title: "PAWSOME VET — Animal Clinic", description: "따뜻한 동물병원 랜딩 페이지", price: 14, category: "pages", tags: ["pet", "vet", "clinic", "korean"], language: "한국어", style: ["dark-theme", "warm", "modern"], layout: "centered", sourceUrl: "https://pawsome-vet.kr", thumbnailUrl: "/templates/pet-clinic/images/fullpage.png", htmlPath: "/templates/pet-clinic/index.html", sections: ["header", "hero", "feature", "stats", "testimonial", "contact", "footer"] },
  { slug: "music-studio", title: "ECHO CHAMBER — Music Production", description: "Cosmic dark music production studio with neon glow effects", price: 18, category: "pages", tags: ["music", "studio", "production", "neon"], language: "English", style: ["dark-theme", "bold", "glow"], layout: "centered", sourceUrl: "https://echo-music.com", thumbnailUrl: "/templates/music-studio/images/fullpage.png", htmlPath: "/templates/music-studio/index.html", sections: ["header", "hero", "feature", "stats", "footer"] },
  { slug: "yacht-club", title: "NAUTILUS — Luxury Yacht Club", description: "Luxury maritime yacht club with fleet showcase", price: 22, category: "pages", tags: ["yacht", "luxury", "maritime", "club"], language: "English", style: ["dark-theme", "elegant", "serif"], layout: "centered", sourceUrl: "https://nautilus-yacht.com", thumbnailUrl: "/templates/yacht-club/images/fullpage.png", htmlPath: "/templates/yacht-club/index.html", sections: ["header", "hero", "feature", "footer"] },
  { slug: "bookstore", title: "CHAPTER ONE — Independent Bookstore", description: "Independent bookstore & cafe with 3D bookshelf display", price: 15, category: "pages", tags: ["bookstore", "cafe", "literary", "warm"], language: "English", style: ["dark-theme", "warm", "serif"], layout: "centered", sourceUrl: "https://chapter-one.com", thumbnailUrl: "/templates/bookstore/images/fullpage.png", htmlPath: "/templates/bookstore/index.html", sections: ["header", "hero", "feature", "stats", "testimonial", "footer"] },
  { slug: "jewelry-atelier", title: "LUMIERE JOAILLERIE — Luxury Jewelry", description: "Ultra-luxe jewelry atelier with sparkle animations", price: 24, category: "pages", tags: ["jewelry", "luxury", "atelier", "sparkle"], language: "English", style: ["dark-theme", "elegant", "glow"], layout: "centered", sourceUrl: "https://lumiere-jewelry.com", thumbnailUrl: "/templates/jewelry-atelier/images/fullpage.png", htmlPath: "/templates/jewelry-atelier/index.html", sections: ["header", "hero", "feature", "stats", "footer"] },
  { slug: "auto-detail", title: "OBSIDIAN AUTO — Premium Detailing", description: "Premium auto detailing studio with before/after slider", price: 16, category: "pages", tags: ["auto", "detailing", "car", "premium"], language: "English", style: ["dark-theme", "bold", "modern"], layout: "centered", sourceUrl: "https://obsidian-auto.com", thumbnailUrl: "/templates/auto-detail/images/fullpage.png", htmlPath: "/templates/auto-detail/index.html", sections: ["header", "hero", "feature", "pricing", "footer"] },
  { slug: "spa-wellness", title: "SERENITY SPA — Wellness Center", description: "스파 & 웰니스 센터 with breathing exercise animation", price: 15, category: "pages", tags: ["spa", "wellness", "healing", "korean"], language: "한국어", style: ["dark-theme", "elegant", "minimal"], layout: "centered", sourceUrl: "https://serenity-spa.kr", thumbnailUrl: "/templates/spa-wellness/images/fullpage.png", htmlPath: "/templates/spa-wellness/index.html", sections: ["header", "hero", "footer"] },
  { slug: "wine-bar", title: "CUVEE — Wine Bar & Tasting Room", description: "와인 바 & 테이스팅 룸 with wine selection grid", price: 18, category: "pages", tags: ["wine", "bar", "tasting", "elegant"], language: "한국어", style: ["dark-theme", "elegant", "warm"], layout: "centered", sourceUrl: "https://cuvee-wine.kr", thumbnailUrl: "/templates/wine-bar/images/fullpage.png", htmlPath: "/templates/wine-bar/index.html", sections: ["header", "hero", "footer"] },
  { slug: "cowork-space", title: "NEXUS HUB — Co-working Space", description: "Modern creative co-working space with glassmorphism design", price: 16, category: "pages", tags: ["coworking", "office", "tech", "modern"], language: "English", style: ["dark-theme", "modern", "gradient"], layout: "centered", sourceUrl: "https://nexus-hub.com", thumbnailUrl: "/templates/cowork-space/images/fullpage.png", htmlPath: "/templates/cowork-space/index.html", sections: ["header", "hero", "feature", "pricing", "testimonial", "footer"] },
  { slug: "tattoo-studio", title: "INK RITUAL — Custom Tattoo Studio", description: "Custom tattoo studio with neon green accents and smoke effects", price: 16, category: "pages", tags: ["tattoo", "body-art", "dark", "neon"], language: "English", style: ["dark-theme", "bold", "glow"], layout: "centered", sourceUrl: "https://ink-ritual.com", thumbnailUrl: "/templates/tattoo-studio/images/fullpage.png", htmlPath: "/templates/tattoo-studio/index.html", sections: ["header", "hero", "feature", "stats", "footer"] },
  { slug: "craft-brewery", title: "HOPCRAFT — Craft Brewery & Taproom", description: "Craft brewery landing with beer menu carousel", price: 16, category: "pages", tags: ["brewery", "beer", "craft", "taproom"], language: "English", style: ["dark-theme", "warm", "bold"], layout: "centered", sourceUrl: "https://hopcraft-brew.com", thumbnailUrl: "/templates/craft-brewery/images/fullpage.png", htmlPath: "/templates/craft-brewery/index.html", sections: ["header", "hero", "feature", "stats", "footer"] },
  { slug: "boutique-hotel", title: "MAISON ETOILE — Boutique Hotel", description: "Luxury boutique hotel with room types gallery", price: 22, category: "pages", tags: ["hotel", "boutique", "luxury", "hospitality"], language: "English", style: ["dark-theme", "elegant", "gradient"], layout: "centered", sourceUrl: "https://maison-etoile.com", thumbnailUrl: "/templates/boutique-hotel/images/fullpage.png", htmlPath: "/templates/boutique-hotel/index.html", sections: ["header", "hero", "feature", "pricing", "footer"] },
  { slug: "art-gallery", title: "VOID GALLERY — Contemporary Art", description: "Brutalist contemporary art gallery with glitch effects", price: 18, category: "pages", tags: ["art", "gallery", "contemporary", "brutalist"], language: "English", style: ["dark-theme", "minimal", "bold"], layout: "centered", sourceUrl: "https://void-gallery.com", thumbnailUrl: "/templates/art-gallery/images/fullpage.png", htmlPath: "/templates/art-gallery/index.html", sections: ["header", "hero", "feature", "stats", "footer"] },
  { slug: "pilates-studio", title: "ALIGN — Pilates & Barre Studio", description: "Elegant pilates studio with class grid and flowing animations", price: 15, category: "pages", tags: ["pilates", "barre", "fitness", "elegant"], language: "English", style: ["dark-theme", "elegant", "modern"], layout: "centered", sourceUrl: "https://align-pilates.com", thumbnailUrl: "/templates/pilates-studio/images/fullpage.png", htmlPath: "/templates/pilates-studio/index.html", sections: ["header", "hero", "feature", "pricing", "footer"] },
  { slug: "organic-farm", title: "TERRA ROOTS — Organic Farm & Market", description: "Organic farm & market with seasonal produce grid", price: 14, category: "pages", tags: ["farm", "organic", "market", "green"], language: "English", style: ["dark-theme", "warm", "modern"], layout: "centered", sourceUrl: "https://terra-roots.com", thumbnailUrl: "/templates/organic-farm/images/fullpage.png", htmlPath: "/templates/organic-farm/index.html", sections: ["header", "hero", "feature", "pricing", "footer"] },
  { slug: "watch-atelier", title: "HOROLOGIE — Luxury Watch Atelier", description: "Luxury watch atelier with gear rotation animations", price: 24, category: "pages", tags: ["watch", "luxury", "atelier", "precision"], language: "English", style: ["dark-theme", "elegant", "serif"], layout: "centered", sourceUrl: "https://horologie-watch.com", thumbnailUrl: "/templates/watch-atelier/images/fullpage.png", htmlPath: "/templates/watch-atelier/index.html", sections: ["header", "hero", "feature", "stats", "footer"] },
  { slug: "ev-station", title: "VOLTEX — EV Charging Hub", description: "Futuristic EV charging hub with electric pulse animations", price: 16, category: "pages", tags: ["ev", "charging", "tech", "futuristic"], language: "English", style: ["dark-theme", "modern", "glow"], layout: "centered", sourceUrl: "https://voltex-ev.com", thumbnailUrl: "/templates/ev-station/images/fullpage.png", htmlPath: "/templates/ev-station/index.html", sections: ["header", "hero", "feature", "stats", "footer"] },
  { slug: "cooking-studio", title: "MISE EN PLACE — Cooking Studio", description: "Private kitchen & cooking studio with chef profiles", price: 15, category: "pages", tags: ["cooking", "kitchen", "studio", "chef"], language: "English", style: ["dark-theme", "warm", "modern"], layout: "centered", sourceUrl: "https://mise-en-place.com", thumbnailUrl: "/templates/cooking-studio/images/fullpage.png", htmlPath: "/templates/cooking-studio/index.html", sections: ["header", "hero", "feature", "pricing", "footer"] },
  { slug: "surf-school", title: "TIDE RIDERS — Surf School", description: "Epic surf school landing with wave animations", price: 15, category: "pages", tags: ["surf", "school", "ocean", "adventure"], language: "English", style: ["dark-theme", "bold", "gradient"], layout: "centered", sourceUrl: "https://tide-riders.com", thumbnailUrl: "/templates/surf-school/images/fullpage.png", htmlPath: "/templates/surf-school/index.html", sections: ["header", "hero", "feature", "pricing", "footer"] },
  { slug: "whiskey-lounge", title: "OAK & EMBER — Whiskey Lounge", description: "Premium whiskey lounge with collection wall", price: 18, category: "pages", tags: ["whiskey", "lounge", "bar", "premium"], language: "English", style: ["dark-theme", "elegant", "warm"], layout: "centered", sourceUrl: "https://oak-ember.com", thumbnailUrl: "/templates/whiskey-lounge/images/fullpage.png", htmlPath: "/templates/whiskey-lounge/index.html", sections: ["header", "hero", "feature", "pricing", "footer"] },
];

async function main() {
  console.log("Seeding database...");

  await prisma.user.upsert({
    where: { email: "admin@homedream.dev" },
    update: { password: "$2b$12$JEXjrwZBp0P5QwZMfusPk.B6lu2z8czwqd.AcjZ3lHVbp.AAJjNWC" },
    create: { email: "admin@homedream.dev", name: "Admin", role: "ADMIN", credits: 9999, password: "$2b$12$JEXjrwZBp0P5QwZMfusPk.B6lu2z8czwqd.AcjZ3lHVbp.AAJjNWC" },
  });

  await prisma.user.upsert({
    where: { email: "demo@homedream.dev" },
    update: {},
    create: { email: "demo@homedream.dev", name: "Demo User", role: "USER", credits: 100, password: "$2b$10$dummyhashfordemouser0001" },
  });

  for (const t of templates) {
    const { sections: sectionCats, ...data } = t;
    const existing = await prisma.template.findUnique({ where: { slug: data.slug } });
    if (existing) { console.log(`  skip: ${data.title}`); continue; }

    const created = await prisma.template.create({
      data: { ...data, viewCount: Math.floor(Math.random() * 500) + 50, likeCount: Math.floor(Math.random() * 100) + 10, saveCount: Math.floor(Math.random() * 80) + 5 },
    });

    for (let i = 0; i < sectionCats.length; i++) {
      const cat = sectionCats[i];
      await prisma.section.create({
        data: {
          slug: `${data.slug}-${cat}-${i}`, title: `${data.slug}-${cat}-${i}`, category: cat, templateId: created.id,
          tags: data.tags, language: data.language, style: data.style, layout: data.layout,
          thumbnailUrl: `/templates/${data.slug}/images/${String(i + 1).padStart(2, "0")}-${cat}.png`,
          price: cat === "hero" ? 8 : cat === "pricing" ? 7 : 5,
          viewCount: Math.floor(Math.random() * 200) + 20, likeCount: Math.floor(Math.random() * 50) + 5, saveCount: Math.floor(Math.random() * 30) + 2, order: i,
        },
      });
    }
    console.log(`  + ${data.title} (${sectionCats.length} sections)`);
  }

  const tc = await prisma.template.count();
  const sc = await prisma.section.count();
  console.log(`\nDone: ${tc} templates, ${sc} sections`);
}

main().then(() => prisma.$disconnect()).catch((e) => { console.error(e); prisma.$disconnect(); process.exit(1); });
